### ISSUE TITLE
wrong links in README.md

### ISSUE THREAD

**Issue by fmux** [sefeoglu/dcat-converter#6]
I believe the three repository links given in README.md are wrong (they each include the parameter `resumptionToken` instead of `metadataPrefix` and have superfluous slashes at the end).

The correct links should read:
```
https://refubium.fu-berlin.de/oai/dnb?verb=ListRecords&metadataPrefix=xMetaDissPlus
```
```
https://api-depositonce.tu-berlin.de/server/oai/request?verb=ListRecords&metadataPrefix=oai_dc
```
```
https://edoc.hu-berlin.de/oai/request/?verb=ListRecords&metadataPrefix=oai_dc
```

**Comment by sefeoglu** [comment]
Thanks for this, I will update readme. I just put them from config file, since I could retrieve them incrementally. It has paging issues.
